spring.datasource.url=jdbc:mysql://localhost:3306/aam?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=hobbit
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true